export const CREATE_TODO = {
  PENDING: "CREATE_TODO_PENDING",
  SUCCESS: "CREATE_TODO_SUCCESS",
  ERROR: "CREATE_TODO_ERROR"
};

export const EDIT_TODO = {
  PENDING: "EDIT_TODO_PENDING",
  SUCCESS: "EDIT_TODO_SUCCESS",
  ERROR: "EDIT_TODO_ERROR"
};

export const GET_TODOS = {
  PENDING: "GET_TODOS_PENDING",
  SUCCESS: "GET_TODOS_SUCCESS",
  ERROR: "GET_TODOS_ERROR"
};

export const DELETE_TODO = {
  PENDING: "DELETE_TODO_PENDING",
  SUCCESS: "DELETE_TODO_SUCCESS",
  ERROR: "DELETE_TODO_ERROR"
};
